### ISSUE TITLE
Docker pull error

### ISSUE THREAD

**Issue by nasiriscript** [0xNeu/Rainbow#2]
سلام متاسفانه هیچکدام از کانتینرها pull نمی شوند و ارور زیر رو میده:

Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io: Temporary failure in name resolution

**Comment by 0xNeu** [comment]
سلام

احتمالا اشکال از سمت پیکربندی DNS سرور باشه. مراحل زیر رو طی کنید:


1. `echo "DNS=1.1.1.1" | sudo tee /etc/systemd/resolved.conf`
2. `sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf`
3. `systemctl reboot`
4. `docker run hello-world`
